window.GLOSSAR=[
["Grundgesamtheit","ana kütle, evren","alle relevanten Einheiten"],
["Stichprobe","örneklem","untersuchte Teilmenge"],
["statistische Einheit","istatistik birimi","Objekt, an dem gemessen wird"],
["Merkmal / Merkmalsausprägung","değişken / değer","Eigenschaft / konkreter Wert"],
["diskret","kesikli","abzählbar viele Werte"],
["stetig","sürekli","jeder Wert in einem Intervall möglich"],
["nominal / ordinal / kardinal (metrisch)","sınıflayıcı / sıralı / oransal-aralıklı","Skalenniveaus"],
["geschichtete Stichprobe","tabakalı örnekleme","in jeder Gruppe zufällig ziehen"],
["Klumpenstichprobe","küme örneklemesi","ganze Gruppen zufällig ziehen"],
["Störvariable","karıştırıcı değişken","beeinflusst, interessiert aber nicht"],
["absolute / relative Häufigkeit","mutlak / göreli frekans","Anzahl / Anteil"],
["kumuliert, Summenhäufigkeit","birikimli frekans","aufaddiert bis zu einem Wert"],
["empirische Verteilungsfunktion","ampirik dağılım fonksiyonu","Anteil ≤ x, Treppenfunktion"],
["Histogramm / Säulendiagramm","histogram / sütun grafiği","Fläche = Anteil / Höhe = Anzahl"],
["Klassenbreite, Klassenmitte","sınıf genişliği, sınıf orta noktası",""],
["Dichte","yoğunluk","Höhe im Histogramm; bei stetigen ZV f(x)"],
["arithmetisches Mittel","aritmetik ortalama",""],
["Median, Modus","medyan, mod",""],
["Quantil, Quartil","yüzdelik (kantil), çeyreklik",""],
["Varianz, Standardabweichung","varyans, standart sapma",""],
["Verschiebungssatz","kaydırma formülü","Var = E(X²) − (EX)²"],
["Interquartilsabstand (IQR)","çeyrekler açıklığı","x0.75 − x0.25"],
["Ausreißer","aykırı değer","mehr als 1.5·IQR von der Box"],
["rechtsschief = linkssteil","sağa çarpık","langer Schwanz rechts"],
["Kontingenztafel","çapraz tablo","gemeinsame Häufigkeiten"],
["Randverteilung","marjinal dağılım","Zeilen-/Spaltensummen"],
["bedingte Verteilung","koşullu dağılım","durch die Bedingungssumme teilen"],
["Kovarianz, Korrelation","kovaryans, korelasyon",""],
["Rangkorrelation (Spearman)","sıra korelasyonu",""],
["Kausalität, Scheinkorrelation","nedensellik, sahte korelasyon",""],
["Ergebnisraum, Ereignis","örnek uzay, olay",""],
["Durchschnitt ∩, Vereinigung ∪, Komplement","kesişim, birleşim, tümleyen",""],
["disjunkt","ayrık","schließen sich aus"],
["bedingte Wahrscheinlichkeit","koşullu olasılık","P(A|B)"],
["stochastisch unabhängig","istatistiksel olarak bağımsız","P(A∩B) = P(A)P(B)"],
["mit / ohne Zurücklegen","iadeli / iadesiz",""],
["Satz der totalen Wahrscheinlichkeit","toplam olasılık teoremi",""],
["Satz von Bayes","Bayes teoremi",""],
["Zufallsvariable","rastgele değişken",""],
["Träger","destek (alabileceği değerler)",""],
["Wahrscheinlichkeitsfunktion","olasılık fonksiyonu","diskret: P(X = x)"],
["Verteilungsfunktion","dağılım fonksiyonu","F(x) = P(X ≤ x)"],
["Erwartungswert","beklenen değer","E(X)"],
["unabhängig und identisch verteilt (iid)","bağımsız ve özdeş dağılımlı",""],
["Binomial-, Poisson-, Exponentialverteilung","binom, Poisson, üstel dağılım",""],
["Gleichverteilung, Normalverteilung","düzgün dağılım, normal dağılım",""],
["standardisieren","standartlaştırmak","(x − μ)/σ"],
["Zentraler Grenzwertsatz","merkezi limit teoremi",""],
["Schätzer, Schätzwert","tahmin edici, tahmin değeri",""],
["Likelihood, Log-Likelihood","olabilirlik, log-olabilirlik",""],
["Maximum-Likelihood-Schätzer","en çok olabilirlik tahmincisi",""],
["ableiten, nullsetzen, auflösen","türev almak, sıfıra eşitlemek, çözmek",""],
["erwartungstreu / unverzerrt","yansız","Bias = 0"],
["Verzerrung (Bias)","yanlılık",""],
["mittlerer quadratischer Fehler (MSE)","ortalama kare hata",""],
["konsistent","tutarlı","MSE → 0"],
["Kerndichteschätzer, Bandbreite","çekirdek yoğunluk tahmini, bant genişliği",""],
["Konfidenzintervall, Konfidenzniveau","güven aralığı, güven düzeyi",""],
["Überdeckungswahrscheinlichkeit","kapsama olasılığı",""],
["Freiheitsgrade","serbestlik derecesi",""],
["Nullhypothese / Alternativhypothese","sıfır / alternatif hipotez",""],
["Teststatistik, Prüfgröße","test istatistiği",""],
["Ablehnbereich (Ablehnungsbereich)","ret bölgesi",""],
["kritischer Wert","kritik değer",""],
["Signifikanzniveau α","anlamlılık düzeyi",""],
["Fehler 1. Art / 2. Art","1. tür / 2. tür hata",""],
["verwerfen / nicht verwerfen","reddetmek / reddedememek","nie „annehmen“ schreiben"],
["statistisch absichern","istatistiksel olarak kanıtlamak","H₁ belegen"],
["einseitig / zweiseitig","tek yönlü / çift yönlü",""],
["Anpassungstest, Unabhängigkeitstest","uyum iyiliği testi, bağımsızlık testi",""],
["Vorzeichentest","işaret testi",""],
["Regression, Residuum","regresyon, artık",""],
["Methode der kleinsten Quadrate (KQ)","en küçük kareler yöntemi",""],
["ceteris paribus (c.p.)","diğer her şey sabitken",""],
["Bestimmtheitsmaß R²","belirlilik katsayısı",""],
["Arbeitsverzeichnis","çalışma dizini","setwd()"],
["Lösungskästchen","cevap kutusu",""],
["Antwortsatz","cevap cümlesi","im B-Teil Pflicht"],
["kaufmännisch runden","standart yuvarlama","ab 5 aufrunden"]
];
