"""Baut Formelsammlung_Statistik.pdf (Teil A) mit Aufgaben-Finder und Seitenzahlen."""
from fs_stat_doc import D
import fs_stat_a, fs_stat_b, fs_stat_c  # noqa: F401  (füllen D)

F = D.F
F("Daten beschreiben (Tag 1)")
F("„Skalenniveau“, „diskret oder stetig“", "ölçek türü, kesikli/sürekli", "1.2,1.3")
F("„Grundgesamtheit“, „statistische Einheit“, „Merkmal“", "evren, birim, değişken", "1.1")
F("„Wie heißt dieses Stichprobenverfahren?“", "örnekleme yöntemi", "1.4")
F("Tabelle mit \\(h_j, f_j, H_j, F_j\\) vervollständigen", "sıklık tablosu tamamla", "2.1")
F("„höchstens“, „mindestens“, „mehr als“, „weniger als“", "≤, ≥, >, < → F'ye çevir", "2.2")
F("„Zeichnen Sie die empirische Verteilungsfunktion“", "ampirik dağılım fonksiyonu", "2.3")
F("„normiertes Histogramm“, „Höhe der Säulen“", "histogram yükseklikleri", "2.4")
F("„Schätzen Sie den Anteil zwischen … und …“", "histogramdan oran oku", "2.5")
F("„Modalklasse“, „rechtsschief“, „Säulendiagramm oder Histogramm“", "modal sınıf, çarpıklık", "2.6")
F("Modus, Median, arithmetisches Mittel", "mod, medyan, ortalama", "3.1,3.2,3.3")
F("„Mittelwert für die klassierten Daten“", "sınıflanmış veri ortalaması", "3.4")
F("Mittelwert mehrerer Gruppen, falscher Wert korrigieren", "ağırlıklı ortalama", "3.5")
F("„Quartil“, „Quantil“, „Dezil“", "kantil (sıra numarası n·α)", "4.1")
F("„empirische Varianz“, „unverzerrte Varianz“, „Standardabweichung“", "varyans (1/n veya 1/(n−1))", "4.2,4.3")
F("„Interquartilsabstand“, Daten in andere Einheit umrechnen", "IQR, birim dönüşümü", "4.4,3.6")
F("„Boxplot“, „Ausreißer“, „Whisker“", "kutu grafiği, aykırı değer", "4.5")
F("„Kontingenztafel“, „Randhäufigkeiten“", "çapraz tablo", "5.1")
F("„Anteil … unter den …“, „Zusammenhang?“", "koşullu oran, bağımlılık", "5.2")
F("„erwartete Häufigkeiten“, „χ²-Koeffizient“", "beklenen sıklık, χ²", "5.3")
F("„Kovarianz“", "kovaryans", "6.1")
F("„Korrelationskoeffizient“, „interpretieren Sie ρ“", "korelasyon ve yorumu", "6.2")
F("„Rangkorrelation nach Spearman“", "sıra korelasyonu", "6.3")
F("„in °F angegeben“ – wie ändern sich Kovarianz/Korrelation?", "birim değişince", "6.4")
F("„… führt zu …“, „Stimmen Sie zu? Begründen Sie“", "nedensellik değil korelasyon", "6.5")
F("Wahrscheinlichkeit")
F("„weder … noch“, „genau eines“, „aber nicht“", "metni kümeye çevir", "7.1")
F("„Ergebnisraum Ω = {…}“, „Mächtigkeiten \\(|A\\cap\\bar B|\\)“", "küme elemanı say", "7.2")
F("„fairer Würfel“, „Laplace“", "eşit olasılıklı deney", "7.3")
F("„Berechnen Sie \\(P(A\\cup B)\\)“, „Gegenereignis“", "olasılık kuralları", "7.4,7.5")
F("„wenn bekannt ist, dass …“, „unter der Bedingung“", "koşullu olasılık", "7.6")
F("„Sind A und B stochastisch unabhängig?“", "bağımsızlık kontrolü", "7.7")
F("„zuerst … dann …“, Anteile und bedingte Anteile", "ağaç diyagramı", "7.8")
F("„zufällig ausgewählt … defekt?“", "toplam olasılık", "7.9")
F("„… ist defekt. Von welcher Maschine stammt es?“", "Bayes: sonuçtan nedene", "7.10")
F("„Prävalenz“, „Sensitivität“, „Spezifität“", "tıbbi test (Bayes)", "7.11")
F("„ohne Zurücklegen“, „Urne“", "geri koymadan çekme", "7.12,0.6")
F("Zufallsvariablen")
F("„Träger“, „Wahrscheinlichkeitsfunktion“", "değerler ve olasılıkları", "8.1")
F("„\\(P(X=x)=c\\cdot\\dots\\) Bestimmen Sie c“", "c'yi bul (toplam = 1)", "8.2")
F("„Vervollständigen Sie F(x)“ (Treppe)", "kesikli dağılım fonksiyonu", "8.3")
F("„gültige Dichtefunktion“, „Bestimmen Sie c“ (stetig)", "yoğunluk, integral = 1", "8.4")
F("„\\(P(X\\le1)\\)“ bei Dichte, „Median der ZV“", "sürekli F(x), medyan", "8.5")
F("„Erwartungswert“, „im Mittel“", "beklenen değer", "8.6")
F("„E(Y) für Y = log(X)“, „\\(E(X^2)\\)“", "fonksiyonun beklentisi", "8.7")
F("„Varianz von X“", "varyans", "8.8")
F("„\\(Z=0.5X+Y\\)“, „E(2X+4)“, „unabhängig“", "E ve Var kuralları", "8.9")
F("gemeinsame Tabelle \\(P(X=x,Y=y)\\), „Randverteilung“", "iki rastgele değişken", "8.10")
F("Verteilungen")
F("„Wie lautet die Verteilung von X?“, „geeignetste Verteilung“", "dağılımı tanı", "9.2,9.1")
F("„n-mal unabhängig“, „Anzahl der Erfolge“, „rät“", "binom", "9.4")
F("„im Durchschnitt … pro Monat/Stunde“", "Poisson", "9.5")
F("„Wartezeit“, „im Mittel 3 Stunden“, „bis zum Defekt“", "üstel (exponential)", "9.8")
F("„gleichverteilt zwischen a und b“", "düzgün dağılım", "9.7")
F("„\\(X\\sim N(\\mu,\\sigma^2)\\)“, „Berechnen Sie \\(P(X\\le\\dots)\\)“", "normal: standartlaştır", "9.9")
F("„Welchen Wert überschreiten nur 5 %?“", "normal kantil", "9.10")
F("„Gesamtgewicht von 10 Packungen“", "normal toplamları", "9.11")
F("„approximative Verteilung von \\(\\bar X\\)“, n groß", "merkezi limit teoremi", "9.12")
F("Schätzen")
F("„Testen Sie, ob der Schätzer unverzerrt ist“", "yansızlık kontrolü", "10.2,10.1")
F("„\\(Var(\\hat\\vartheta)\\)“, „MSE“, „konsistent“, „vorzuziehen“", "tahminci karşılaştırma", "10.3,10.4")
F("„Kerndichteschätzer an der Stelle x“", "çekirdek yoğunluk tahmini", "10.5")
F("„Approximations-/Schätzfehler“, „asymptotisch“", "bias-varyans", "10.6")
F("„Stellen Sie die (Log-)Likelihood auf“", "ML reçetesi", "11.1")
F("„Beobachtet wurden … Likelihood?“", "somut örneklemde L", "11.2")
F("ML für Poisson / Bernoulli / Exponential / geometrisch / normal", "standart ML sonuçları", "11.3,11.4,11.5,11.6,11.7")
F("ML mit ungewöhnlicher Dichte, \\(x^b\\), \\(2^{x\\beta}\\)", "özel yoğunluklar", "11.8")
F("„\\(P(X=1)=\\alpha,\\ P(X=2)=\\alpha^2\\)“", "tablodan ML", "11.9")
F("„Bedingung zweiter Ordnung“", "ikinci türev", "11.1,11.10")
F("Konfidenzintervalle und Tests")
F("„Konfidenzintervall“ – Aussagen richtig/falsch", "güven aralığı yorumu", "12.1")
F("KI für μ (σ bekannt / unbekannt)", "ortalama için GA", "12.2,12.3")
F("KI für Anteil / Varianz", "oran / varyans için GA", "12.4,12.5")
F("„Wie groß muss n sein?“, „Was steckt in diesem R-Befehl?“", "örneklem büyüklüğü", "12.6")
F("„statistisch absichern“, „Hypothesenpaar“", "H₀ ve H₁ kur", "13.1")
F("„Fehler 1./2. Art“", "hata türleri", "13.2")
F("„Ablehnungsbereich“, „kritischer Wert“", "ret bölgesi", "13.3")
F("„p-Wert“, „zu α = 1 %, 5 %, 10 %“", "p-değeri ve karar", "13.4")
F("„Varianz bekannt“ + Mittelwert testen", "Gauß testi", "13.5")
F("„Varianz unbekannt“, t.test-Output", "t testi", "13.6")
F("„Anteil“ testen (n groß / klein)", "binom testi", "13.7,13.8")
F("„Streuung“, „Varianz größer als“ testen", "varyans testi", "13.9")
F("„ohne Verteilungsannahme“, „Median“", "işaret testi", "13.10")
F("„unabhängig?“ mit Kontingenztafel testen", "χ² bağımsızlık testi", "13.11")
F("„Ist der Würfel fair?“", "χ² uyum testi", "13.12")
F("„Welcher Test ist geeignet?“", "test seçimi", "13.13")
F("Regression")
F("„Regressionsgerade nach der Methode der kleinsten Quadrate“", "en küçük kareler doğrusu", "14.1")
F("„Interpretieren Sie \\(\\hat\\beta_1\\)“, „Prognose“, „Residuen“", "yorum, tahmin, kalıntı", "14.2")
F("„Bestimmtheitsmaß R²“", "açıklanan varyans", "14.3")
F("R-Output „Coefficients … Pr(&gt;|t|)“", "lm çıktısı, anlamlılık", "14.4")

if __name__ == "__main__":
    D.build()
