"""Baut Formelsammlung_R.pdf (Teil B): R-Beispiele ausführen, Finder, Seitenzahlen."""
import os, subprocess
from fs_r import D
from fs_r_run import run_all
from fscommon import SRC

F = D.F
F("Start und Einlesen")
F("„Setzen Sie mittels setwd(path.expand(\"~\")) Ihr Working Directory“", "çalışma klasörünü ayarla", "2.1")
F("„Speichern Sie die Daten als Data-Frame-Objekt d“", "veriyi oku (sep, dec, header)", "2.1,2.2")
F("„Geben Sie die ersten 6 Zeilen wieder“, „Wie viele Beobachtungen?“", "head, dim, nrow", "2.3")
F("„Ermitteln Sie die Objekttypen der Variablen …“", "değişken türü", "2.7,1.6")
F("„nur die Beobachtungen aus …“, „Kämpfe mit mindestens …“", "satır seç, alt veri", "2.4,2.5")
F("„Ergänzen Sie den Data Frame um eine Spalte …“", "yeni sütun", "2.6,8.1")
F("Vektor, Folge, Wiederholung erstellen", "c, seq, rep", "1.2")
F("„Wie viele Werte …?“, „Anteil der Werte …“", "TRUE/FALSE say", "1.5")
F("Vereinigung, Schnittmenge, Differenz (Testat 0)", "küme işlemleri", "1.9")
F("Faktor, Levels, fehlende Werte NA", "faktör, NA", "1.7,1.8")
F("Matrix oder Tafel von Hand eingeben", "matris, data frame", "1.11")
F("Kennzahlen")
F("„arithmetisches Mittel und unverzerrter Schätzer der Standardabweichung“", "mean, sd", "3.1")
F("„empirische Varianz“ (Nenner n)", "ampirik varyans", "3.2")
F("Median, Quartile, IQR, Spannweite", "median, quantile, IQR", "3.3")
F("„Häufigkeiten“, „häufigste Ausprägung“", "table, prop.table, mod", "3.4")
F("„… für jedes Tal/Fach mit einem einzigen Befehl“", "grup bazında hesap", "3.5")
F("„Klassieren Sie … in die Klassen …“", "cut ile sınıflandırma", "3.6")
F("„Kontingenztafel“, „Randhäufigkeiten“, „Anteil … unter …“", "çapraz tablo, addmargins", "3.7")
F("„Korrelation“, „linearer Zusammenhang“, „Spearman“", "cor, cov", "3.8")
F("Grafiken")
F("„Speichern Sie Ihre Grafik als .pdf-Datei“", "pdf() … dev.off()", "4.1")
F("„Histogramm“, „Intervallgrenzen [a, b)“, „Dichte“", "hist: breaks, right, freq", "4.2")
F("„Boxplot“, „getrennt nach …“", "boxplot", "4.3")
F("„Streudiagramm“, „Regressionsgerade einzeichnen“", "plot, abline", "4.4")
F("„Kerndichteschätzer“, „Bandbreite“, „Epanechnikov“", "density", "4.5")
F("„Säulendiagramm“, „empirische Verteilungsfunktion“", "barplot, ecdf", "4.6")
F("„Zeichnen Sie die Wahrscheinlichkeitsfunktion / Dichte“", "dbinom ile plot, curve", "4.7")
F("Verteilungen und Simulation")
F("Welcher R-Befehl für welche Verteilung? Parameter?", "d/p/q/r ve parametreler", "5.1")
F("„höchstens“, „mindestens“, „mehr als“ in R", "pbinom/pnorm'a çevir", "5.2")
F("Binomial / Poisson / Normal in R", "dbinom, ppois, pnorm", "5.3,5.4,5.5")
F("Exponential, Gleichverteilung, t- und χ²-Quantile", "pexp, punif, qt, qchisq", "5.6")
F("„Simulieren Sie …“, „set.seed“, Lückentext rbinom", "rastgele sayı", "6.1")
F("„Simulieren Sie 1 000 Stichproben … Mittelwert“", "replicate, ZGWS", "6.2")
F("Urne, mit/ohne Zurücklegen", "sample, dhyper", "6.3")
F("Programmieren")
F("„Schreiben Sie eine Funktion …“", "function", "7.1")
F("„für alle Werte von … bis …“, Schleife", "for, sapply", "7.2,7.4")
F("„Falls …, sonst …“", "if, ifelse", "7.3")
F("Zahl/Text aus Ziffern zusammensetzen (Yennefer-Typ)", "paste0 döngüsü", "7.5")
F("Maximum-Likelihood")
F("„Spalte iL20 mit individuellen Likelihoods“, „Likelihood aller Beobachtungen“", "tekil ve toplam likelihood", "8.1")
F("„in der Form X × 10^Y“", "bilimsel gösterim", "8.1")
F("„Funktion Likelihood.pois(lambda, x)“, „für alle Werte … ML-Schätzer“", "ızgara araması", "8.2")
F("Likelihood ist 0, „Log-Likelihood“", "log-likelihood", "8.3")
F("„numerisch maximieren“, ein Parameter", "optimise", "8.4")
F("„mit nlm“, zwei Parameter, „Startwerte“, „rücktransformiert“", "nlm, exp dönüşümü", "8.5")
F("„Stellen Sie die Likelihood grafisch dar“", "likelihood grafiği", "8.6")
F("Konfidenzintervalle und Tests")
F("„95 %-Konfidenzintervall für den Erwartungswert“", "ortalama için GA", "9.1")
F("KI für Anteil oder Varianz", "oran / varyans GA", "9.2")
F("„Überprüfen Sie die Behauptung mit einem geeigneten Test“, t.test-Output", "t.test", "9.3")
F("Teststatistik, kritischer Wert, p-Wert „von Hand“ in R", "qnorm, pnorm, pt", "9.4")
F("Binomialtest, „7 von 8“", "binom.test, pbinom", "9.5")
F("„unabhängig?“, Kontingenztafel testen; „fair?“", "chisq.test", "9.6")
F("Varianz testen", "pchisq", "9.7")
F("Regression und Fehler")
F("„Schätzen Sie ein lineares Regressionsmodell“, summary lesen", "lm, summary", "10.1")
F("Prognose, Residuen, R², KI für Koeffizienten", "predict, residuals, confint", "10.2")
F("Runden, X × 10^Y, sprintf", "yuvarlama, bilimsel gösterim", "1.12")
F("„die drei größten …“, „Welche … am meisten?“, „wie viele verschiedene …“", "sırala, en büyük, unique", "2.8")
F("Data Frame selbst erstellen / speichern", "data.frame, write.csv", "2.9")
F("„Anteil der Beobachtungen mit höchstens …“, F̂(x), Quantil nach Vorlesung", "ecdf, quantile type=2", "3.9")
F("„Standardisieren Sie …“", "z-değerleri", "3.10")
F("Zusatzlinien, Legende, Achsenbereich, Farben", "lines, curve, legend, xlim", "4.8")
F("„grafisch prüfen, ob normalverteilt“", "qqnorm", "4.9")
F("Möglichkeiten zählen, Laplace, Bayes nachrechnen", "choose, expand.grid", "5.7")
F("Dichte als Funktion schreiben, ML numerisch", "kendi dichte + optimise", "8.7")
F("ML-Schätzer Bernoulli/Poisson/Exponential/Normal direkt", "hazır formüller", "8.8")
F("„Unterscheiden sich die Mittelwerte zweier Gruppen?“", "iki örneklem t-testi", "9.8")
F("„80 von 100 …“, Anteil testen, KI für Anteil", "prop.test, binom.test", "9.9")
F("Komplette Klausur")
F("Ganze Teil-B-Klausur (a–h) Schritt für Schritt", "tam sınav çözümü", "11.1,11.2,11.3,11.4")
F("Histogramm, Likelihood, Gitter, Yennefer-Funktion am Klausurbeispiel", "sınavın e–h kısımları", "11.5,11.6,11.7,11.8")
F("Antwortsätze für alle Aufgabentypen", "hazır cümleler", "12.1,12.2,12.3,12.4,12.5")
F("Error in …", "hata mesajları", "13.1")


if __name__ == "__main__":
    subprocess.run(["Rscript", "fs_r_figs.R"], cwd=os.path.join(SRC, "rwork"), check=True, capture_output=True)
    n = run_all(D)
    print(n, "R-Chunks ausgeführt")
    D.build()
