setwd("../../uebungsdaten")
d <- read.csv("Fitness.csv")
print(head(d)); print(class(d$Studio)); print(class(d$Besuche))
print(round(median(d$Minuten),3)); print(round(IQR(d$Minuten),3)); print(quantile(d$Minuten,c(.25,.75)))
print(table(d$Studio, d$Abo)); print(round(prop.table(table(d$Studio, d$Abo), margin=1),3))
d$iL04 <- dexp(d$Wartezeit, rate=0.4); L <- prod(d$iL04); print(L)
Likelihood.exp <- function(lambda, x) prod(dexp(x, rate=lambda))
lam <- seq(0.30, 0.60, by=0.05); Ls <- sapply(lam, Likelihood.exp, x=d$Wartezeit); print(cbind(lam, Ls)); print(lam[which.max(Ls)]); print(1/mean(d$Wartezeit))
print(t.test(d$Minuten, mu=70, alternative="less"))
print(round(mean(d$Minuten),3)); print(round(sd(d$Minuten),3))
