# Probeklausur 4: Datensatz Kaffee.csv (Semikolon + Dezimalkomma!) und Kontrollrechnungen
set.seed(2024)
n <- 90
Stadtteil <- sample(c("Innenstadt","Weende","Grone"), n, TRUE, prob=c(.45,.3,.25))
Getraenk <- sample(c("Espresso","Cappuccino","Latte"), n, TRUE, prob=c(.3,.4,.3))
Preis <- round(c(Espresso=2.2, Cappuccino=3.3, Latte=3.8)[Getraenk] + rnorm(n, 0, 0.35) + ifelse(Stadtteil=="Innenstadt", 0.2, 0), 2)
Wartezeit <- pmin(pmax(round(rexp(n, 0.3), 1), 0.1), 15.9)
Bewertung <- pmin(5, pmax(1, round(rnorm(n, c(Innenstadt=3.6, Weende=3.9, Grone=3.4)[Stadtteil], 0.9))))
d <- data.frame(Bestellung=sprintf("K%03d",1:n), Stadtteil, Getraenk, Preis, Wartezeit, Bewertung=as.integer(Bewertung))
write.csv2(d, "../../uebungsdaten/Kaffee.csv", row.names=FALSE)
d <- read.csv("../../uebungsdaten/Kaffee.csv", sep=";", dec=",")
print(head(d)); print(sapply(d, class))
cat("mean Preis", round(mean(d$Preis),3), " emp var", round(mean((d$Preis-mean(d$Preis))^2),3), " var", round(var(d$Preis),3), "\n")
print(range(d$Wartezeit)); print(round(tapply(d$Bewertung, d$Stadtteil, mean),3))
tab <- table(d$Getraenk, d$Stadtteil); print(tab); print(chisq.test(tab))
logLik.exp <- function(lambda, x) sum(dexp(x, rate=lambda, log=TRUE))
lam <- seq(0.1, 0.5, by=0.05); ll <- sapply(lam, logLik.exp, x=d$Wartezeit); print(round(cbind(lam, ll),3)); print(lam[which.max(ll)])
print(optimise(logLik.exp, c(0.01, 2), x=d$Wartezeit, maximum=TRUE)); print(1/mean(d$Wartezeit))
cap <- d$Preis[d$Getraenk=="Cappuccino"]; print(t.test(cap, mu=3.2, alternative="greater"))
